// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8vAjC_jSMG7F6LrDK0uDJ8amLXZSpK4E',
    appId: '1:630068168616:web:b0d30cfb0d9be8ebf87f9d',
    messagingSenderId: '630068168616',
    projectId: 'weather-c6bdb',
    authDomain: 'weather-c6bdb.firebaseapp.com',
    storageBucket: 'weather-c6bdb.appspot.com',
    measurementId: 'G-166N1QD1G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPCzzqjXbJeINaMrymPiE19dKNUbSj-EE',
    appId: '1:630068168616:android:6d3b779fe3cad662f87f9d',
    messagingSenderId: '630068168616',
    projectId: 'weather-c6bdb',
    storageBucket: 'weather-c6bdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvIHBVl-QkWv_jEbqq5lYfpyEWfeclZrk',
    appId: '1:630068168616:ios:dbc092223048b0a1f87f9d',
    messagingSenderId: '630068168616',
    projectId: 'weather-c6bdb',
    storageBucket: 'weather-c6bdb.appspot.com',
    iosBundleId: 'com.example.flutterAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvIHBVl-QkWv_jEbqq5lYfpyEWfeclZrk',
    appId: '1:630068168616:ios:d3a047738ca213f7f87f9d',
    messagingSenderId: '630068168616',
    projectId: 'weather-c6bdb',
    storageBucket: 'weather-c6bdb.appspot.com',
    iosBundleId: 'com.example.flutterAssignment.RunnerTests',
  );
}
